databases:
  - name: Task-app_DB
    databaseName: task_app_db_meak
    user: task-app-back
    region: singapore

services:
  - type: web
    name: task-app-back
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Task-app_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
